In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [2]:
data = pd.read_csv('Processing.csv')
data

text  label
0    ['riezf', 'kresseek', 'santai', 'gojek', 'chat...    1.0
1    ['prifad', 'gue', 'gojek', 'iya', 'semoga', 't...    1.0
2    ['kooalee', 'sepe', 'i', 'gojek', 'gue', 'error']    0.0
3    ['beralih', 'grab', 'gojek', 'yahudi', 'kaget'...    0.0
4    ['minggu', 'sepi', 'order', 'sesepi', 'gojek',...    0.0
..                                                 ...    ...
495  ['by', 'the', 'way', 'abang', 'grab', 'car', '...    1.0
496  ['gila', 'jelek', 'banget', 'gue', 'grab', 'me...    0.0
497  ['angin', 'hujan', 'transaksi', 'grab', 'beli'...    0.0
498  ['care', 'gue', 'grab', 'hypertext', 'transfer...    1.0
499                           ['abang', 'grab', 'nya']    0.0

[500 rows x 2 columns]

In [3]:
count = CountVectorizer()
titles = pd.read_csv('Processing.csv', sep=',' ,usecols=['text'], squeeze=True)
docs = titles.values
bag = count.fit_transform(docs)
print(docs)

["['riezf', 'kresseek', 'santai', 'gojek', 'chat', 'worst', 'case', 'tinggal', 'fitur', 'peduli', 'lindungi']"
 "['prifad', 'gue', 'gojek', 'iya', 'semoga', 'turun', 'berdua', 'menang']"
 "['kooalee', 'sepe', 'i', 'gojek', 'gue', 'error']"
 "['beralih', 'grab', 'gojek', 'yahudi', 'kaget', 'mam', 'bakso', 'k', 'ya', 'bilang', 'biaya', 'hidup', 'daerah', 'murah', 'gelut']"
 "['minggu', 'sepi', 'order', 'sesepi', 'gojek', 'food', 'rekan', 'pesan', 'menit', 'order', 'jalan', 'jalan', 'kemana', 'wkwk']"
 "['menemukan', 'gojek', 'jakarta', 'ky', 'hypertext', 'transfer', 'protocol', 'over', 'secure', 'socket', 'layer', 't', 'co', 'tspdytycb']"
 "['gojek', 'ku', 'promo', 'gofoodnya', 'hypertext', 'transfer', 'protocol', 'over', 'secure', 'socket', 'layer', 't', 'co', 'dxcnfoapw']"
 "['k', 'kelas', 'k', 'wkwk', 'eh', 'uang', 'ongkos', 'angkutan', 'kota', 'i', 'iritt', 'gojek', 'uang', 'jajan', 'habis', 'bayar', 'gojek', 'sajaa']"
 "['bt', 'banget', 'penumpang', 'gojek', 'naikan', 'gojek', 'gue'

In [4]:
type(docs)
docs.shape

(500,)

In [5]:
print(count.vocabulary_)

{'riezf': 1484, 'kresseek': 918, 'santai': 1510, 'gojek': 585, 'chat': 312, 'worst': 1854, 'case': 303, 'tinggal': 1737, 'fitur': 512, 'peduli': 1338, 'lindungi': 979, 'prifad': 1420, 'gue': 617, 'iya': 732, 'semoga': 1559, 'turun': 1777, 'berdua': 202, 'menang': 1077, 'kooalee': 909, 'sepe': 1572, 'error': 492, 'beralih': 192, 'grab': 598, 'yahudi': 1869, 'kaget': 786, 'mam': 1028, 'bakso': 131, 'ya': 1868, 'bilang': 233, 'biaya': 228, 'hidup': 666, 'daerah': 360, 'murah': 1189, 'gelut': 564, 'minggu': 1154, 'sepi': 1575, 'order': 1299, 'sesepi': 1584, 'food': 519, 'rekan': 1469, 'pesan': 1386, 'menit': 1116, 'jalan': 744, 'kemana': 835, 'wkwk': 1849, 'menemukan': 1089, 'jakarta': 742, 'ky': 933, 'hypertext': 684, 'transfer': 1759, 'protocol': 1430, 'over': 1305, 'secure': 1535, 'socket': 1625, 'layer': 958, 'co': 329, 'tspdytycb': 1768, 'ku': 922, 'promo': 1425, 'gofoodnya': 584, 'dxcnfoapw': 471, 'kelas': 829, 'eh': 477, 'uang': 1784, 'ongkos': 1286, 'angkutan': 74, 'kota': 914, 'ir

In [6]:
print(count.get_feature_names())
a=count.get_feature_names()

['aaaaaa', 'aaaaakh', 'aariichaaaaan', 'abai', 'abang', 'abangnya', 'abg', 'acara', 'acungi', 'adakan', 'adik', 'admin', 'admirablerenjun', 'aduh', 'aerox', 'aggresif', 'agung', 'ah', 'ahengtri', 'ahzek', 'aikyjqt', 'air', 'airasia', 'airlanggafess', 'ajaaaaaaaa', 'ajak', 'aji', 'akal', 'akbar', 'akses', 'aktifin', 'akuaccy', 'akucapekbanget', 'akun', 'akunku', 'akunya', 'akur', 'al', 'alamat', 'alasan', 'alcaponneeee', 'alfa', 'alhamdulillah', 'alhasil', 'alias', 'alif', 'alih', 'alinithia', 'alkaff', 'allah', 'alohabbyri', 'also', 'always', 'aman', 'amang', 'amannya', 'ambil', 'ambilkan', 'amin', 'amp', 'an', 'anak', 'anaknya', 'ancol', 'ancrit', 'and', 'andalan', 'aneehh', 'aneh', 'ang', 'anggap', 'anggung', 'angin', 'angkat', 'angkutan', 'anjc', 'anjeer', 'anjenggg', 'anjing', 'anjinggg', 'anjir', 'anjj', 'anjrit', 'anjritttt', 'anjrrrr', 'another', 'anta', 'anter', 'antriannya', 'anu', 'apapun', 'apes', 'aplicator', 'aplikasi', 'aplikasinyya', 'aplk', 'app', 'apply', 'arah', 'arah

c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [7]:
print(bag.toarray())
b = bag.toarray()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
dfa = pd.DataFrame(data=a)
num_rows = -1
for row in open("Processing.csv"):
    num_rows +=1
    
dfb = pd.DataFrame(data=b, index=range(0, num_rows), columns=[a])
dfb

aaaaaa aaaaakh aariichaaaaan abai abang abangnya abg acara acungi adakan  \
0        0       0             0    0     0        0   0     0      0      0   
1        0       0             0    0     0        0   0     0      0      0   
2        0       0             0    0     0        0   0     0      0      0   
3        0       0             0    0     0        0   0     0      0      0   
4        0       0             0    0     0        0   0     0      0      0   
..     ...     ...           ...  ...   ...      ...  ..   ...    ...    ...   
495      0       0             0    0     1        0   0     0      0      0   
496      0       0             0    0     0        0   0     0      0      0   
497      0       0             0    0     0        0   0     0      0      0   
498      0       0             0    0     0        0   0     0      0      0   
499      0       0             0    0     1        0   0     0      0      0   

     ... ya yahudi yeoxjack ygy your yourrbabbyy yoyakarta yrlwof zolim zxiyan  
0    ...  0      0        0   0    0           0         0      0     0      0  
1    ...  0      0        0   0    0           0         0      0     0      0  
2    ...  0      0        0   0    0           0         0      0     0      0  
3    ...  1      1        0   0    0           0         0      0     0      0  
4    ...  0      0        0   0    0           0         0      0     0      0  
..   ... ..    ...      ...  ..  ...         ...       ...    ...   ...    ...  
495  ...  0      0        0   0    0           0         0      0     0      0  
496  ...  0      0        0   0    0           0         0      0     0      0  
497  ...  0      0        0   0    0           0         0      0     0      0  
498  ...  0      0        0   0    0           0         0      0     0      0  
499  ...  0      0        0   0    0           0         0      0     0      0  

[500 rows x 1878 columns]

In [9]:
dfb.to_excel("PembobotanTF.xlsx")  

In [10]:
tfidf = TfidfTransformer(use_idf=True,
                         norm ='l2',
                         smooth_idf=True)

tf = tfidf.fit_transform(count.fit_transform(docs)).toarray()

num_rows = -1
for row in open("Processing.csv"):
    num_rows +=1
    
dfbtf = pd.DataFrame(data=tf, index=range(0,num_rows), columns=[a])
dfbtf

aaaaaa aaaaakh aariichaaaaan abai     abang abangnya  abg acara acungi  \
0      0.0     0.0           0.0  0.0  0.000000      0.0  0.0   0.0    0.0   
1      0.0     0.0           0.0  0.0  0.000000      0.0  0.0   0.0    0.0   
2      0.0     0.0           0.0  0.0  0.000000      0.0  0.0   0.0    0.0   
3      0.0     0.0           0.0  0.0  0.000000      0.0  0.0   0.0    0.0   
4      0.0     0.0           0.0  0.0  0.000000      0.0  0.0   0.0    0.0   
..     ...     ...           ...  ...       ...      ...  ...   ...    ...   
495    0.0     0.0           0.0  0.0  0.127273      0.0  0.0   0.0    0.0   
496    0.0     0.0           0.0  0.0  0.000000      0.0  0.0   0.0    0.0   
497    0.0     0.0           0.0  0.0  0.000000      0.0  0.0   0.0    0.0   
498    0.0     0.0           0.0  0.0  0.000000      0.0  0.0   0.0    0.0   
499    0.0     0.0           0.0  0.0  0.703910      0.0  0.0   0.0    0.0   

    adakan  ...        ya    yahudi yeoxjack  ygy your yourrbabbyy yoyakarta  \
0      0.0  ...  0.000000  0.000000      0.0  0.0  0.0         0.0       0.0   
1      0.0  ...  0.000000  0.000000      0.0  0.0  0.0         0.0       0.0   
2      0.0  ...  0.000000  0.000000      0.0  0.0  0.0         0.0       0.0   
3      0.0  ...  0.156613  0.321929      0.0  0.0  0.0         0.0       0.0   
4      0.0  ...  0.000000  0.000000      0.0  0.0  0.0         0.0       0.0   
..     ...  ...       ...       ...      ...  ...  ...         ...       ...   
495    0.0  ...  0.000000  0.000000      0.0  0.0  0.0         0.0       0.0   
496    0.0  ...  0.000000  0.000000      0.0  0.0  0.0         0.0       0.0   
497    0.0  ...  0.000000  0.000000      0.0  0.0  0.0         0.0       0.0   
498    0.0  ...  0.000000  0.000000      0.0  0.0  0.0         0.0       0.0   
499    0.0  ...  0.000000  0.000000      0.0  0.0  0.0         0.0       0.0   

    yrlwof zolim zxiyan  
0      0.0   0.0    0.0  
1      0.0   0.0    0.0  
2      0.0   0.0    0.0  
3      0.0   0.0    0.0  
4      0.0   0.0    0.0  
..     ...   ...    ...  
495    0.0   0.0    0.0  
496    0.0   0.0    0.0  
497    0.0   0.0    0.0  
498    0.0   0.0    0.0  
499    0.0   0.0    0.0  

[500 rows x 1878 columns]

In [11]:
dfbtf.to_excel("PembobotanTF-IDF.xlsx")  

In [20]:
a = tfidf.fit_transform(count.fit_transform(docs)).toarray()
a.shape
print('tf_idf kata "abang"', a[(1,124)])

tf_idf kata "abang" 0.0
